version: "3.8"

services:
  # =========================
  # DATABASE
  # =========================
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2009"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5000:5432"
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # =========================
  # RABBITMQ
  # =========================
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  # =========================
  # AUTH – MIGRATIONS
  # =========================
  auth-migrations:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/auth_db
    command:
      [
        "node",
        "node_modules/typeorm/cli.js",
        "-d",
        "dist/data-source.js",
        "migration:run",
      ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appnet

  # =========================
  # TASKS – MIGRATIONS
  # =========================
  tasks-migrations:
    build:
      context: .
      dockerfile: apps/tasks-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/tasks_db
    command:
      [
        "node",
        "node_modules/typeorm/cli.js",
        "-d",
        "dist/data-source.js",
        "migration:run",
      ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appnet

  # =========================
  # NOTIFICATIONS – MIGRATIONS
  # =========================
  notifications-migrations:
    build:
      context: .
      dockerfile: apps/notifications-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/notifications_db
    command:
      [
        "node",
        "node_modules/typeorm/cli.js",
        "-d",
        "dist/data-source.js",
        "migration:run",
      ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appnet

  # =========================
  # AUTH SERVICE
  # =========================
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    environment:
      JWT_SECRET: ${JWT_SECRET:-FIVN129SX0D8KJSHF8WJH29DJF8WJH29DJSF8WJH2}
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/auth_db
    depends_on:
      auth-migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - appnet

  # =========================
  # TASKS SERVICE
  # =========================
  tasks-service:
    build:
      context: .
      dockerfile: apps/tasks-service/Dockerfile
    environment:
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/tasks_db
    depends_on:
      tasks-migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - appnet

  # =========================
  # NOTIFICATIONS SERVICE
  # =========================
  notifications-service:
    build:
      context: .
      dockerfile: apps/notifications-service/Dockerfile
    environment:
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/notifications_db
    depends_on:
      notifications-migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - appnet

  # =========================
  # API GATEWAY
  # =========================
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-FIVN129SX0D8KJSHF8WJH29DJF8WJH29DJSF8WJH2}
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3000:3000"
    depends_on:
      auth-service:
        condition: service_started
      tasks-service:
        condition: service_started
      notifications-service:
        condition: service_started
    networks:
      - appnet

  # =========================
  # FRONTEND
  # =========================
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - "5173:80"
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - appnet

volumes:
  pgdata:
  rabbitmq_data:
  rabbitmq_log:

networks:
  appnet:
    driver: bridge
