services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api_gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      JWT_SECRET: FIVN129SX0D8KJSHF8WJH29DJF8WJH29DJSF8WJH2
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      FRONTEND_URL: http://web:5173
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - task_manager_net

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth_service
    environment:
      JWT_SECRET: FIVN129SX0D8KJSHF8WJH29DJF8WJH29DJSF8WJH2
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/auth_db
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - task_manager_net

  tasks-service:
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
    container_name: tasks_service
    environment:
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/tasks_db
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - task_manager_net

  notifications-service:
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
    container_name: notifications_service
    environment:
      RMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:2009@postgres:5432/notifications_db
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - task_manager_net

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: web_app
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://api-gateway:3000
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - task_manager_net

  postgres:
    image: postgres:16-alpine
    container_name: task_manager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2009
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - task_manager_net

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: task_manager_rabbitmq
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - task_manager_net

networks:
  task_manager_net:
    driver: bridge

volumes:
  postgres_data:
